### ISSUE TITLE
Error when sending large files

### ISSUE THREAD

**Issue by LiXiang0723** [playay/ws2s#1]
I was trying to send a large file (about 302KB in base64 format using "sendb" command ) to the ws2s server.It gave me following error:
```
Exception happened during processing of request from ('127.0.0.1', 54231)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Library/Python/2.7/site-packages/ws2s/websocket_server.py", line 162, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/Library/Python/2.7/site-packages/ws2s/websocket_server.py", line 175, in handle
    self.read_next_message()
  File "/Library/Python/2.7/site-packages/ws2s/websocket_server.py", line 235, in read_next_message
    opcode_handler(self, message_bytes.decode('utf8'))
  File "/Library/Python/2.7/site-packages/ws2s/websocket_server.py", line 121, in _message_received_
    self.message_received(self.handler_to_client(handler), self, msg)
  File "/Library/Python/2.7/site-packages/ws2s/ws2s_server.py", line 37, in message_received_wrapper
    if response_message:
UnboundLocalError: local variable 'response_message' referenced before assignment
```

Small files works fine. Any help?

**Comment by playay** [comment]
sorry for the late reply. I just saw this notifiction. 

when sending message by webocket, the safe length of message usually should Less than 127K byte (2 header + 125 payload)

by the way, can you speak Chinese?

我这边想出一个解决方案，抽时间实现的话，估计要一个月后了。。

1. send 和 sendb 方法增加一个可选参数，指定 消息id。在 onRecv 方法中也返回 消息id。
2. send 和 sendb 方法内部，封装对长消息的分段发送的逻辑。

**Comment by playay** [comment]
fixed in this [commit](https://github.com/playay/ws2s/commit/8de6e16a204cac9f7864e5b1f751ef84f880f2ac) . also see  this [pull request](https://github.com/Pithikos/python-websocket-server/pull/70)


large file is avaliable  on version ">=2.1.5" .

thanks for you issues.
